2022-03-06 11:15:29,087 - config.doExcel - INFO - 开始获取[elementDate.xlsx]的[elementsInfo]表
2022-03-06 11:15:29,102 - config.doExcel - INFO - 开始获取[elementDate.xlsx]的[loginData]表
2022-03-06 11:15:29,102 - config.doExcel - INFO - 创建表[loginData]的数据字典
2022-03-06 11:15:30,425 - common.myUnit - INFO - 打开浏览器
2022-03-06 11:15:30,427 - common.myUnit - INFO - ************************ 开始执行测试用例 ************************
2022-03-06 11:15:30,768 - pageObject.basePage - INFO - 成功进入http://127.0.0.1:8081/login 
2022-03-06 11:15:30,970 - pageObject.basePage - INFO - http://127.0.0.1:8081/login 加载成功!
2022-03-06 11:15:30,970 - testLogin - INFO -    *** 登录测试用例：loginTest-01 开启密码登陆的教师账号和正确的密码 ***
2022-03-06 11:15:31,084 - pageObject.basePage - INFO - 输入 [admin]
2022-03-06 11:15:31,172 - pageObject.basePage - INFO - 输入 [123456]
2022-03-06 11:15:31,587 - pageObject.basePage - INFO - 点击Sign in
2022-03-06 11:15:33,157 - testLogin - INFO - 登录测试用例 loginTest-01 测试用例通过！
2022-03-06 11:15:33,157 - pageObject.basePage - ERROR - 未能保存通过截图
Traceback (most recent call last):
  File "D:\Software\PycharmProjects\sccProjects\pageObject\basePage.py", line 278, in saveScreenShot
    self.driver.save_screenshot(os.path.join(conf.passImagePath,filename))
AttributeError: 'ConfigParser' object has no attribute 'passImagePath'
2022-03-06 11:15:33,861 - common.myUnit - INFO - ************************ 测试用例执行结束 ************************
2022-03-06 11:15:33,861 - common.myUnit - INFO - ************************ 开始执行测试用例 ************************
2022-03-06 11:15:34,092 - pageObject.basePage - INFO - 成功进入http://127.0.0.1:8081/login 
2022-03-06 11:15:34,095 - pageObject.basePage - INFO - http://127.0.0.1:8081/login 加载成功!
2022-03-06 11:15:34,096 - testLogin - INFO -    *** 登录测试用例：loginTest-02 开启密码登陆的教师账号和错误的密码 ***
2022-03-06 11:15:44,629 - pageObject.basePage - ERROR - 元素定位超时：('id', 'username')
Traceback (most recent call last):
  File "D:\Software\PycharmProjects\sccProjects\pageObject\basePage.py", line 61, in findElement
    WebDriverWait(self.driver,10).until(EC.visibility_of_element_located(loc))
  File "D:\Software\python\Anaconda\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2022-03-06 11:15:45,349 - common.myUnit - INFO - ************************ 测试用例执行结束 ************************
2022-03-06 11:15:47,537 - common.myUnit - INFO - 退出浏览器
